import AppKit
import UniformTypeIdentifiers
import ImageIO
public enum Capture: Sendable {
    case text(String), image([String: Data]), ignored
}
public enum ClipboardCodec {
    private static let rasterTypes = Set(CGImageSourceCopyTypeIdentifiers() as! [String])
    public static let ownType = NSPasteboard.PasteboardType("com.clipnest.private")
    public static func capture(_ pb: NSPasteboard) throws -> Capture {
        let blocked = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", ownType.rawValue]
        guard !(pb.types ?? []).contains(where: { blocked.contains($0.rawValue) || $0.rawValue.lowercased().contains("concealed") }) else { return .ignored }
        for item in pb.pasteboardItems ?? [] {
            let types = item.types.filter { type in
                guard type != .fileURL, rasterTypes.contains(type.rawValue), let uti = UTType(type.rawValue) else { return false }
                return uti.conforms(to: .image)
            }
            guard !types.isEmpty else { continue }
            var images: [String: Data] = [:]; var size = 0
            for type in types {
                if let data = item.data(forType: type) {
                    size += data.count; guard size <= 20 * 1024 * 1024 else { throw StoreError.tooLarge }
                    images[type.rawValue] = data
                }
            }
            if !images.isEmpty { return .image(images) }
        }
        if let text = pb.string(forType: .string) { guard text.utf8.count <= 1024 * 1024 else { throw StoreError.tooLarge }; return .text(text) }
        return .ignored
    }
    public static func item(entry: Entry, store: HistoryStore, formatted: String? = nil) throws -> NSPasteboardItem {
        let item = NSPasteboardItem()
        if let text = formatted ?? entry.text { item.setString(text, forType: .string) }
        else {
            for rep in entry.images { item.setData(try Data(contentsOf: store.imageURL(rep.file), options: .mappedIfSafe), forType: NSPasteboard.PasteboardType(rep.type)) }
        }
        item.setString("ClipNest", forType: ownType)
        return item
    }
}
